# Generated by Django 3.0.5 on 2020-06-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInGallery',
        ),
    ]
