# Generated by Django 3.0.5 on 2020-06-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_productingallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productingallery',
            name='created',
        ),
        migrations.RemoveField(
            model_name='productingallery',
            name='updated',
        ),
        migrations.AddField(
            model_name='productingallery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
