# Generated by Django 3.0.7 on 2020-07-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20200608_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productingallery',
            options={'verbose_name': 'Товар в слайдере для галереи', 'verbose_name_plural': 'Товары в слайдере для галереи'},
        ),
        migrations.RemoveField(
            model_name='productingallery',
            name='session_key',
        ),
    ]
