# Generated by Django 3.0.7 on 2020-07-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200707_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInGallery',
        ),
    ]
