# Generated by Django 3.0.7 on 2020-07-17 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200717_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fragrance_family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.FragranceFamilyOfProduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.MakerOfProduct'),
        ),
    ]
