# Generated by Django 3.0.7 on 2020-07-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200717_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeOfProduct',
            new_name='ConcentrationOfProduct',
        ),
    ]
